// Curated mock jobs + internships dataset for CareerNova.AI
export type JobType = "Full-time" | "Internship" | "Contract" | "Part-time";
export type WorkMode = "Remote" | "Hybrid" | "On-site";
export type Experience = "Internship" | "Entry" | "Mid" | "Senior";

export type Job = {
  id: string;
  title: string;
  company: string;
  logo: string; // emoji or single char
  location: string;
  remote: WorkMode;
  type: JobType;
  experience: Experience;
  salary: string;
  salaryMin: number; // in k USD or k INR equivalent for filtering
  stipend?: string;
  duration?: string;
  skills: string[];
  category: string; // matches career key family e.g. "frontend", "ai", "data"
  description: string;
  responsibilities: string[];
  benefits: string[];
  postedDate: string; // relative
  postedAt: number; // ms epoch for sorting
  applyUrl: string;
  source: "LinkedIn" | "Wellfound" | "Internshala" | "Indeed" | "Naukri" | "Glassdoor";
  companyAbout: string;
  matchHints: string[]; // career keys this fits
};

const now = Date.now();
const days = (n: number) => now - n * 86400000;

const ext = {
  linkedin: (q: string) => `https://www.linkedin.com/jobs/search/?keywords=${encodeURIComponent(q)}`,
  wellfound: (q: string) => `https://wellfound.com/jobs?q=${encodeURIComponent(q)}`,
  internshala: (q: string) =>
    `https://internshala.com/internships/keywords-${encodeURIComponent(q.toLowerCase().replace(/\s+/g, "-"))}`,
  indeed: (q: string) => `https://www.indeed.com/jobs?q=${encodeURIComponent(q)}`,
  naukri: (q: string) => `https://www.naukri.com/${encodeURIComponent(q.toLowerCase().replace(/\s+/g, "-"))}-jobs`,
  glassdoor: (q: string) => `https://www.glassdoor.com/Job/jobs.htm?sc.keyword=${encodeURIComponent(q)}`,
};

export const popularLocations = [
  { name: "Bangalore", emoji: "🇮🇳", count: 1240, hue: 295 },
  { name: "Mumbai", emoji: "🌊", count: 870, hue: 200 },
  { name: "Pune", emoji: "🏙️", count: 540, hue: 30 },
  { name: "Hyderabad", emoji: "💎", count: 720, hue: 160 },
  { name: "Delhi", emoji: "🏛️", count: 660, hue: 350 },
  { name: "Remote", emoji: "🌐", count: 2100, hue: 280 },
  { name: "Dubai", emoji: "🏜️", count: 310, hue: 50 },
  { name: "Singapore", emoji: "🦁", count: 280, hue: 10 },
  { name: "London", emoji: "🎡", count: 410, hue: 220 },
  { name: "USA Remote", emoji: "🗽", count: 980, hue: 250 },
];

export const jobs: Job[] = [
  {
    id: "j1",
    title: "Frontend Engineer",
    company: "Vercel",
    logo: "▲",
    location: "Remote",
    remote: "Remote",
    type: "Full-time",
    experience: "Mid",
    salary: "$120k – $160k",
    salaryMin: 120,
    skills: ["React", "TypeScript", "Next.js", "TailwindCSS"],
    category: "frontend",
    description:
      "Build the future of the web at Vercel. Work on developer-facing tools used by millions of engineers worldwide.",
    responsibilities: [
      "Ship pixel-perfect, accessible UI in React and Next.js",
      "Collaborate with designers on motion-rich interfaces",
      "Optimize Core Web Vitals and runtime performance",
    ],
    benefits: ["Equity", "Top-tier hardware", "Unlimited PTO", "Learning stipend"],
    postedDate: "2d ago",
    postedAt: days(2),
    applyUrl: ext.linkedin("Frontend Engineer Vercel"),
    source: "LinkedIn",
    companyAbout: "Vercel is the platform for frontend developers, providing speed and reliability for the modern web.",
    matchHints: ["frontend", "fullstack"],
  },
  {
    id: "j2",
    title: "AI Engineer",
    company: "OpenAI",
    logo: "✦",
    location: "USA Remote",
    remote: "Remote",
    type: "Full-time",
    experience: "Senior",
    salary: "$220k – $320k",
    salaryMin: 220,
    skills: ["Python", "PyTorch", "LLMs", "RAG", "Distributed Systems"],
    category: "ai",
    description:
      "Push the frontier of AI. Build, train, and deploy large-scale models that change how people work and create.",
    responsibilities: [
      "Design and train large language models",
      "Build evaluation harnesses and inference pipelines",
      "Collaborate with research and product teams",
    ],
    benefits: ["Equity", "Health & wellness", "401k match", "Compute credits"],
    postedDate: "1d ago",
    postedAt: days(1),
    applyUrl: ext.linkedin("AI Engineer OpenAI"),
    source: "LinkedIn",
    companyAbout: "OpenAI's mission is to ensure that artificial general intelligence benefits all of humanity.",
    matchHints: ["ai", "data"],
  },
  {
    id: "j3",
    title: "Full Stack Developer",
    company: "Razorpay",
    logo: "₹",
    location: "Bangalore",
    remote: "Hybrid",
    type: "Full-time",
    experience: "Mid",
    salary: "₹24L – ₹38L",
    salaryMin: 90,
    skills: ["Node.js", "React", "PostgreSQL", "AWS"],
    category: "fullstack",
    description: "Power India's payments infrastructure. Ship features that move billions in transactions monthly.",
    responsibilities: [
      "Own end-to-end product features",
      "Design scalable APIs and data models",
      "Mentor junior engineers",
    ],
    benefits: ["ESOPs", "Wellness budget", "Hybrid work", "Conference sponsorship"],
    postedDate: "3d ago",
    postedAt: days(3),
    applyUrl: ext.naukri("Full Stack Developer Razorpay"),
    source: "Naukri",
    companyAbout: "Razorpay is India's leading payments and banking platform for businesses.",
    matchHints: ["fullstack", "frontend", "backend"],
  },
  {
    id: "j4",
    title: "Product Designer",
    company: "Linear",
    logo: "L",
    location: "Remote",
    remote: "Remote",
    type: "Full-time",
    experience: "Mid",
    salary: "$140k – $190k",
    salaryMin: 140,
    skills: ["Figma", "Motion", "Design Systems", "Prototyping"],
    category: "design",
    description: "Design the tool the best software teams use to build their products. Obsess over craft and detail.",
    responsibilities: [
      "Own complex product surfaces end-to-end",
      "Build and evolve our design system",
      "Prototype micro-interactions in Framer",
    ],
    benefits: ["Equity", "Remote-first", "Annual offsite", "Top tools"],
    postedDate: "4d ago",
    postedAt: days(4),
    applyUrl: ext.wellfound("Product Designer Linear"),
    source: "Wellfound",
    companyAbout: "Linear is a purpose-built tool for planning and building products, used by the world's best teams.",
    matchHints: ["design"],
  },
  {
    id: "j5",
    title: "Data Scientist",
    company: "Stripe",
    logo: "S",
    location: "Singapore",
    remote: "Hybrid",
    type: "Full-time",
    experience: "Senior",
    salary: "$180k – $240k",
    salaryMin: 180,
    skills: ["Python", "SQL", "Statistics", "ML", "Experimentation"],
    category: "data",
    description:
      "Use data to shape the future of online commerce. Build models that detect fraud at internet scale.",
    responsibilities: [
      "Design and run experiments",
      "Build ML models for fraud detection",
      "Translate insights into product decisions",
    ],
    benefits: ["Equity", "Relocation", "Premium health", "Stripe credits"],
    postedDate: "5d ago",
    postedAt: days(5),
    applyUrl: ext.linkedin("Data Scientist Stripe"),
    source: "LinkedIn",
    companyAbout: "Stripe is a financial infrastructure platform for businesses of every size.",
    matchHints: ["data", "ai"],
  },
  {
    id: "j6",
    title: "DevOps Engineer",
    company: "Cloudflare",
    logo: "☁︎",
    location: "London",
    remote: "Hybrid",
    type: "Full-time",
    experience: "Mid",
    salary: "£75k – £110k",
    salaryMin: 100,
    skills: ["Kubernetes", "Terraform", "AWS", "CI/CD", "Linux"],
    category: "devops",
    description: "Run one of the fastest networks on Earth. Ship reliability improvements that affect millions of sites.",
    responsibilities: [
      "Operate global Kubernetes clusters",
      "Improve deployment pipelines",
      "Lead incident response",
    ],
    benefits: ["RSUs", "Hybrid", "Gym", "Internet stipend"],
    postedDate: "6d ago",
    postedAt: days(6),
    applyUrl: ext.glassdoor("DevOps Engineer Cloudflare"),
    source: "Glassdoor",
    companyAbout: "Cloudflare's mission is to help build a better Internet.",
    matchHints: ["devops", "backend"],
  },
  {
    id: "j7",
    title: "Cybersecurity Analyst",
    company: "TCS",
    logo: "T",
    location: "Hyderabad",
    remote: "On-site",
    type: "Full-time",
    experience: "Entry",
    salary: "₹8L – ₹14L",
    salaryMin: 70,
    skills: ["Networking", "SIEM", "Python", "Linux"],
    category: "cybersec",
    description: "Defend enterprise systems against modern threats. Monitor, investigate, and respond to incidents.",
    responsibilities: ["Monitor SIEM dashboards", "Triage alerts", "Document incidents"],
    benefits: ["Health insurance", "Cab service", "Training certifications"],
    postedDate: "1w ago",
    postedAt: days(7),
    applyUrl: ext.naukri("Cybersecurity Analyst"),
    source: "Naukri",
    companyAbout: "TCS is a global leader in IT services, consulting, and business solutions.",
    matchHints: ["cybersec"],
  },
  {
    id: "j8",
    title: "Mobile Developer (React Native)",
    company: "Swiggy",
    logo: "🍔",
    location: "Bangalore",
    remote: "Hybrid",
    type: "Full-time",
    experience: "Mid",
    salary: "₹20L – ₹32L",
    salaryMin: 80,
    skills: ["React Native", "TypeScript", "iOS", "Android"],
    category: "mobile",
    description: "Build the app millions order food on every day. Care deeply about smooth UX on flaky networks.",
    responsibilities: ["Build cross-platform features", "Optimize app performance", "Work with native modules"],
    benefits: ["ESOPs", "Meals", "Hybrid"],
    postedDate: "2d ago",
    postedAt: days(2),
    applyUrl: ext.linkedin("React Native Developer Swiggy"),
    source: "LinkedIn",
    companyAbout: "Swiggy is India's largest on-demand convenience platform.",
    matchHints: ["mobile", "frontend"],
  },
  {
    id: "j9",
    title: "Cloud Solutions Architect",
    company: "AWS",
    logo: "🟧",
    location: "Dubai",
    remote: "Hybrid",
    type: "Full-time",
    experience: "Senior",
    salary: "$160k – $220k",
    salaryMin: 160,
    skills: ["AWS", "Architecture", "Networking", "Security"],
    category: "cloud",
    description: "Help enterprises in MENA build on AWS. Design solutions that scale to millions of users.",
    responsibilities: ["Design cloud architectures", "Lead workshops", "Guide enterprise migrations"],
    benefits: ["Stock", "Relocation", "Insurance"],
    postedDate: "3d ago",
    postedAt: days(3),
    applyUrl: ext.linkedin("Solutions Architect AWS"),
    source: "LinkedIn",
    companyAbout: "Amazon Web Services is the world's most comprehensive cloud platform.",
    matchHints: ["cloud", "devops"],
  },
  {
    id: "j10",
    title: "Blockchain Engineer",
    company: "Polygon",
    logo: "◆",
    location: "Remote",
    remote: "Remote",
    type: "Full-time",
    experience: "Mid",
    salary: "$130k – $200k",
    salaryMin: 130,
    skills: ["Solidity", "Rust", "EVM", "ZK Proofs"],
    category: "blockchain",
    description: "Build the infrastructure scaling Ethereum to billions of users.",
    responsibilities: ["Develop smart contracts", "Audit code", "Contribute to protocol"],
    benefits: ["Token grants", "Remote", "Conference budget"],
    postedDate: "1w ago",
    postedAt: days(7),
    applyUrl: ext.wellfound("Blockchain Engineer Polygon"),
    source: "Wellfound",
    companyAbout: "Polygon is a decentralized Ethereum scaling platform.",
    matchHints: ["blockchain"],
  },

  // ===== Internships =====
  {
    id: "i1",
    title: "Frontend Developer Intern",
    company: "Zomato",
    logo: "🍕",
    location: "Remote",
    remote: "Remote",
    type: "Internship",
    experience: "Internship",
    salary: "Stipend",
    salaryMin: 0,
    stipend: "₹25,000/month",
    duration: "6 months",
    skills: ["React", "JavaScript", "CSS"],
    category: "frontend",
    description: "Work alongside senior engineers shipping features for one of India's most loved apps.",
    responsibilities: ["Build UI components", "Fix bugs", "Write tests"],
    benefits: ["Stipend", "Pre-placement offer", "Mentorship"],
    postedDate: "1d ago",
    postedAt: days(1),
    applyUrl: ext.internshala("Frontend Developer"),
    source: "Internshala",
    companyAbout: "Zomato connects millions of users with restaurants worldwide.",
    matchHints: ["frontend"],
  },
  {
    id: "i2",
    title: "Machine Learning Intern",
    company: "Microsoft Research",
    logo: "M",
    location: "Bangalore",
    remote: "Hybrid",
    type: "Internship",
    experience: "Internship",
    salary: "Stipend",
    salaryMin: 0,
    stipend: "₹80,000/month",
    duration: "3 months",
    skills: ["Python", "PyTorch", "Research", "ML"],
    category: "ai",
    description: "Contribute to cutting-edge research projects in NLP and computer vision.",
    responsibilities: ["Run experiments", "Co-author papers", "Present results"],
    benefits: ["Stipend", "Research mentor", "Compute access"],
    postedDate: "2d ago",
    postedAt: days(2),
    applyUrl: ext.linkedin("ML Intern Microsoft Research"),
    source: "LinkedIn",
    companyAbout: "Microsoft Research drives world-changing research across computing.",
    matchHints: ["ai", "data"],
  },
  {
    id: "i3",
    title: "UI/UX Design Intern",
    company: "CRED",
    logo: "C",
    location: "Bangalore",
    remote: "Hybrid",
    type: "Internship",
    experience: "Internship",
    salary: "Stipend",
    salaryMin: 0,
    stipend: "₹40,000/month",
    duration: "6 months",
    skills: ["Figma", "Visual Design", "Prototyping"],
    category: "design",
    description: "Design experiences for India's most premium financial product.",
    responsibilities: ["Design flows", "Build prototypes", "Run user tests"],
    benefits: ["Stipend", "Design mentorship", "Premium tools"],
    postedDate: "4d ago",
    postedAt: days(4),
    applyUrl: ext.internshala("UI UX Design"),
    source: "Internshala",
    companyAbout: "CRED is a members-only club rewarding India's most trustworthy.",
    matchHints: ["design"],
  },
  {
    id: "i4",
    title: "Data Analyst Intern",
    company: "Flipkart",
    logo: "F",
    location: "Bangalore",
    remote: "On-site",
    type: "Internship",
    experience: "Internship",
    salary: "Stipend",
    salaryMin: 0,
    stipend: "₹50,000/month",
    duration: "6 months",
    skills: ["SQL", "Python", "Excel", "Tableau"],
    category: "data",
    description: "Turn billions of data points into product decisions for India's largest e-commerce platform.",
    responsibilities: ["Build dashboards", "Run analyses", "Present insights"],
    benefits: ["Stipend", "PPO chance", "Mentorship"],
    postedDate: "5d ago",
    postedAt: days(5),
    applyUrl: ext.internshala("Data Analyst"),
    source: "Internshala",
    companyAbout: "Flipkart is India's homegrown e-commerce leader.",
    matchHints: ["data"],
  },
  {
    id: "i5",
    title: "Backend Developer Intern",
    company: "GitHub",
    logo: "🐙",
    location: "USA Remote",
    remote: "Remote",
    type: "Internship",
    experience: "Internship",
    salary: "Stipend",
    salaryMin: 0,
    stipend: "$8,000/month",
    duration: "12 weeks",
    skills: ["Ruby", "Go", "PostgreSQL", "APIs"],
    category: "backend",
    description: "Work on services powering 100M+ developers around the world.",
    responsibilities: ["Build internal APIs", "Improve reliability", "Contribute to OSS"],
    benefits: ["Stipend", "Relocation help", "Swag"],
    postedDate: "6d ago",
    postedAt: days(6),
    applyUrl: ext.linkedin("Backend Intern GitHub"),
    source: "LinkedIn",
    companyAbout: "GitHub is where the world builds software.",
    matchHints: ["backend", "fullstack"],
  },
  {
    id: "i6",
    title: "Cybersecurity Intern",
    company: "Deloitte",
    logo: "D",
    location: "Mumbai",
    remote: "On-site",
    type: "Internship",
    experience: "Internship",
    salary: "Stipend",
    salaryMin: 0,
    stipend: "₹35,000/month",
    duration: "3 months",
    skills: ["Networking", "Security", "Linux"],
    category: "cybersec",
    description: "Assist consulting teams on real-world security audits for enterprise clients.",
    responsibilities: ["Pentest assistance", "Report writing", "Tool research"],
    benefits: ["Stipend", "Certifications", "PPO chance"],
    postedDate: "1w ago",
    postedAt: days(7),
    applyUrl: ext.internshala("Cybersecurity"),
    source: "Internshala",
    companyAbout: "Deloitte is a global consulting and audit leader.",
    matchHints: ["cybersec"],
  },
];

export const allSkills = Array.from(new Set(jobs.flatMap((j) => j.skills))).sort();
export const allLocations = Array.from(new Set(jobs.map((j) => j.location))).sort();
