/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAssessRouteImport } from './routes/dashboard.assess'
import { Route as DashboardCareersRouteImport } from './routes/dashboard.careers'
import { Route as DashboardCollegesRouteImport } from './routes/dashboard.colleges'
import { Route as DashboardCompareRouteImport } from './routes/dashboard.compare'
import { Route as DashboardDirectionsRouteImport } from './routes/dashboard.directions'
import { Route as DashboardGovtPathwaysRouteImport } from './routes/dashboard.govt-pathways'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardJourneyRouteImport } from './routes/dashboard.journey'
import { Route as DashboardMentorRouteImport } from './routes/dashboard.mentor'
import { Route as DashboardNextstepRouteImport } from './routes/dashboard.nextstep'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardQuizRouteImport } from './routes/dashboard.quiz'
import { Route as DashboardResourcesRouteImport } from './routes/dashboard.resources'
import { Route as DashboardResumeRouteImport } from './routes/dashboard.resume'
import { Route as DashboardRoadmapsRouteImport } from './routes/dashboard.roadmaps'
import { Route as DashboardSkillsRouteImport } from './routes/dashboard.skills'
import { Route as DashboardStreamsRouteImport } from './routes/dashboard.streams'
import { Route as DashboardDirectionsIndexRouteImport } from './routes/dashboard.directions.index'
import { Route as DashboardDirectionsKeyRouteImport } from './routes/dashboard.directions.$key'
import { Route as DashboardOutcomesKeyRouteImport } from './routes/dashboard.outcomes.$key'
import { Route as DashboardRoadmapKeyRouteImport } from './routes/dashboard.roadmap.$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssessRoute = DashboardAssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCareersRoute = DashboardCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCollegesRoute = DashboardCollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompareRoute = DashboardCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDirectionsRoute = DashboardDirectionsRouteImport.update({
  id: '/directions',
  path: '/directions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGovtPathwaysRoute = DashboardGovtPathwaysRouteImport.update({
  id: '/govt-pathways',
  path: '/govt-pathways',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJourneyRoute = DashboardJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMentorRoute = DashboardMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNextstepRoute = DashboardNextstepRouteImport.update({
  id: '/nextstep',
  path: '/nextstep',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuizRoute = DashboardQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResourcesRoute = DashboardResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeRoute = DashboardResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoadmapsRoute = DashboardRoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSkillsRoute = DashboardSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStreamsRoute = DashboardStreamsRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDirectionsIndexRoute =
  DashboardDirectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDirectionsRoute,
  } as any)
const DashboardDirectionsKeyRoute = DashboardDirectionsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => DashboardDirectionsRoute,
} as any)
const DashboardOutcomesKeyRoute = DashboardOutcomesKeyRouteImport.update({
  id: '/outcomes/$key',
  path: '/outcomes/$key',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoadmapKeyRoute = DashboardRoadmapKeyRouteImport.update({
  id: '/roadmap/$key',
  path: '/roadmap/$key',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/assess': typeof DashboardAssessRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/colleges': typeof DashboardCollegesRoute
  '/dashboard/compare': typeof DashboardCompareRoute
  '/dashboard/directions': typeof DashboardDirectionsRouteWithChildren
  '/dashboard/govt-pathways': typeof DashboardGovtPathwaysRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/journey': typeof DashboardJourneyRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/nextstep': typeof DashboardNextstepRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/quiz': typeof DashboardQuizRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/roadmaps': typeof DashboardRoadmapsRoute
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/dashboard/streams': typeof DashboardStreamsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/directions/$key': typeof DashboardDirectionsKeyRoute
  '/dashboard/outcomes/$key': typeof DashboardOutcomesKeyRoute
  '/dashboard/roadmap/$key': typeof DashboardRoadmapKeyRoute
  '/dashboard/directions/': typeof DashboardDirectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/assess': typeof DashboardAssessRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/colleges': typeof DashboardCollegesRoute
  '/dashboard/compare': typeof DashboardCompareRoute
  '/dashboard/govt-pathways': typeof DashboardGovtPathwaysRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/journey': typeof DashboardJourneyRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/nextstep': typeof DashboardNextstepRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/quiz': typeof DashboardQuizRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/roadmaps': typeof DashboardRoadmapsRoute
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/dashboard/streams': typeof DashboardStreamsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/directions/$key': typeof DashboardDirectionsKeyRoute
  '/dashboard/outcomes/$key': typeof DashboardOutcomesKeyRoute
  '/dashboard/roadmap/$key': typeof DashboardRoadmapKeyRoute
  '/dashboard/directions': typeof DashboardDirectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/assess': typeof DashboardAssessRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/colleges': typeof DashboardCollegesRoute
  '/dashboard/compare': typeof DashboardCompareRoute
  '/dashboard/directions': typeof DashboardDirectionsRouteWithChildren
  '/dashboard/govt-pathways': typeof DashboardGovtPathwaysRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/journey': typeof DashboardJourneyRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/nextstep': typeof DashboardNextstepRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/quiz': typeof DashboardQuizRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/roadmaps': typeof DashboardRoadmapsRoute
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/dashboard/streams': typeof DashboardStreamsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/directions/$key': typeof DashboardDirectionsKeyRoute
  '/dashboard/outcomes/$key': typeof DashboardOutcomesKeyRoute
  '/dashboard/roadmap/$key': typeof DashboardRoadmapKeyRoute
  '/dashboard/directions/': typeof DashboardDirectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/assess'
    | '/dashboard/careers'
    | '/dashboard/colleges'
    | '/dashboard/compare'
    | '/dashboard/directions'
    | '/dashboard/govt-pathways'
    | '/dashboard/jobs'
    | '/dashboard/journey'
    | '/dashboard/mentor'
    | '/dashboard/nextstep'
    | '/dashboard/profile'
    | '/dashboard/quiz'
    | '/dashboard/resources'
    | '/dashboard/resume'
    | '/dashboard/roadmaps'
    | '/dashboard/skills'
    | '/dashboard/streams'
    | '/dashboard/'
    | '/dashboard/directions/$key'
    | '/dashboard/outcomes/$key'
    | '/dashboard/roadmap/$key'
    | '/dashboard/directions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/assess'
    | '/dashboard/careers'
    | '/dashboard/colleges'
    | '/dashboard/compare'
    | '/dashboard/govt-pathways'
    | '/dashboard/jobs'
    | '/dashboard/journey'
    | '/dashboard/mentor'
    | '/dashboard/nextstep'
    | '/dashboard/profile'
    | '/dashboard/quiz'
    | '/dashboard/resources'
    | '/dashboard/resume'
    | '/dashboard/roadmaps'
    | '/dashboard/skills'
    | '/dashboard/streams'
    | '/dashboard'
    | '/dashboard/directions/$key'
    | '/dashboard/outcomes/$key'
    | '/dashboard/roadmap/$key'
    | '/dashboard/directions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/assess'
    | '/dashboard/careers'
    | '/dashboard/colleges'
    | '/dashboard/compare'
    | '/dashboard/directions'
    | '/dashboard/govt-pathways'
    | '/dashboard/jobs'
    | '/dashboard/journey'
    | '/dashboard/mentor'
    | '/dashboard/nextstep'
    | '/dashboard/profile'
    | '/dashboard/quiz'
    | '/dashboard/resources'
    | '/dashboard/resume'
    | '/dashboard/roadmaps'
    | '/dashboard/skills'
    | '/dashboard/streams'
    | '/dashboard/'
    | '/dashboard/directions/$key'
    | '/dashboard/outcomes/$key'
    | '/dashboard/roadmap/$key'
    | '/dashboard/directions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assess': {
      id: '/dashboard/assess'
      path: '/assess'
      fullPath: '/dashboard/assess'
      preLoaderRoute: typeof DashboardAssessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/careers': {
      id: '/dashboard/careers'
      path: '/careers'
      fullPath: '/dashboard/careers'
      preLoaderRoute: typeof DashboardCareersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/colleges': {
      id: '/dashboard/colleges'
      path: '/colleges'
      fullPath: '/dashboard/colleges'
      preLoaderRoute: typeof DashboardCollegesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/compare': {
      id: '/dashboard/compare'
      path: '/compare'
      fullPath: '/dashboard/compare'
      preLoaderRoute: typeof DashboardCompareRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/directions': {
      id: '/dashboard/directions'
      path: '/directions'
      fullPath: '/dashboard/directions'
      preLoaderRoute: typeof DashboardDirectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/govt-pathways': {
      id: '/dashboard/govt-pathways'
      path: '/govt-pathways'
      fullPath: '/dashboard/govt-pathways'
      preLoaderRoute: typeof DashboardGovtPathwaysRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/journey': {
      id: '/dashboard/journey'
      path: '/journey'
      fullPath: '/dashboard/journey'
      preLoaderRoute: typeof DashboardJourneyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mentor': {
      id: '/dashboard/mentor'
      path: '/mentor'
      fullPath: '/dashboard/mentor'
      preLoaderRoute: typeof DashboardMentorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/nextstep': {
      id: '/dashboard/nextstep'
      path: '/nextstep'
      fullPath: '/dashboard/nextstep'
      preLoaderRoute: typeof DashboardNextstepRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quiz': {
      id: '/dashboard/quiz'
      path: '/quiz'
      fullPath: '/dashboard/quiz'
      preLoaderRoute: typeof DashboardQuizRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resources': {
      id: '/dashboard/resources'
      path: '/resources'
      fullPath: '/dashboard/resources'
      preLoaderRoute: typeof DashboardResourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume': {
      id: '/dashboard/resume'
      path: '/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof DashboardResumeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roadmaps': {
      id: '/dashboard/roadmaps'
      path: '/roadmaps'
      fullPath: '/dashboard/roadmaps'
      preLoaderRoute: typeof DashboardRoadmapsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/skills': {
      id: '/dashboard/skills'
      path: '/skills'
      fullPath: '/dashboard/skills'
      preLoaderRoute: typeof DashboardSkillsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/streams': {
      id: '/dashboard/streams'
      path: '/streams'
      fullPath: '/dashboard/streams'
      preLoaderRoute: typeof DashboardStreamsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/directions/': {
      id: '/dashboard/directions/'
      path: '/'
      fullPath: '/dashboard/directions/'
      preLoaderRoute: typeof DashboardDirectionsIndexRouteImport
      parentRoute: typeof DashboardDirectionsRoute
    }
    '/dashboard/directions/$key': {
      id: '/dashboard/directions/$key'
      path: '/$key'
      fullPath: '/dashboard/directions/$key'
      preLoaderRoute: typeof DashboardDirectionsKeyRouteImport
      parentRoute: typeof DashboardDirectionsRoute
    }
    '/dashboard/outcomes/$key': {
      id: '/dashboard/outcomes/$key'
      path: '/outcomes/$key'
      fullPath: '/dashboard/outcomes/$key'
      preLoaderRoute: typeof DashboardOutcomesKeyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roadmap/$key': {
      id: '/dashboard/roadmap/$key'
      path: '/roadmap/$key'
      fullPath: '/dashboard/roadmap/$key'
      preLoaderRoute: typeof DashboardRoadmapKeyRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardDirectionsRouteChildren {
  DashboardDirectionsKeyRoute: typeof DashboardDirectionsKeyRoute
  DashboardDirectionsIndexRoute: typeof DashboardDirectionsIndexRoute
}

const DashboardDirectionsRouteChildren: DashboardDirectionsRouteChildren = {
  DashboardDirectionsKeyRoute: DashboardDirectionsKeyRoute,
  DashboardDirectionsIndexRoute: DashboardDirectionsIndexRoute,
}

const DashboardDirectionsRouteWithChildren =
  DashboardDirectionsRoute._addFileChildren(DashboardDirectionsRouteChildren)

interface DashboardRouteChildren {
  DashboardAssessRoute: typeof DashboardAssessRoute
  DashboardCareersRoute: typeof DashboardCareersRoute
  DashboardCollegesRoute: typeof DashboardCollegesRoute
  DashboardCompareRoute: typeof DashboardCompareRoute
  DashboardDirectionsRoute: typeof DashboardDirectionsRouteWithChildren
  DashboardGovtPathwaysRoute: typeof DashboardGovtPathwaysRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardJourneyRoute: typeof DashboardJourneyRoute
  DashboardMentorRoute: typeof DashboardMentorRoute
  DashboardNextstepRoute: typeof DashboardNextstepRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardQuizRoute: typeof DashboardQuizRoute
  DashboardResourcesRoute: typeof DashboardResourcesRoute
  DashboardResumeRoute: typeof DashboardResumeRoute
  DashboardRoadmapsRoute: typeof DashboardRoadmapsRoute
  DashboardSkillsRoute: typeof DashboardSkillsRoute
  DashboardStreamsRoute: typeof DashboardStreamsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardOutcomesKeyRoute: typeof DashboardOutcomesKeyRoute
  DashboardRoadmapKeyRoute: typeof DashboardRoadmapKeyRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssessRoute: DashboardAssessRoute,
  DashboardCareersRoute: DashboardCareersRoute,
  DashboardCollegesRoute: DashboardCollegesRoute,
  DashboardCompareRoute: DashboardCompareRoute,
  DashboardDirectionsRoute: DashboardDirectionsRouteWithChildren,
  DashboardGovtPathwaysRoute: DashboardGovtPathwaysRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardJourneyRoute: DashboardJourneyRoute,
  DashboardMentorRoute: DashboardMentorRoute,
  DashboardNextstepRoute: DashboardNextstepRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardQuizRoute: DashboardQuizRoute,
  DashboardResourcesRoute: DashboardResourcesRoute,
  DashboardResumeRoute: DashboardResumeRoute,
  DashboardRoadmapsRoute: DashboardRoadmapsRoute,
  DashboardSkillsRoute: DashboardSkillsRoute,
  DashboardStreamsRoute: DashboardStreamsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOutcomesKeyRoute: DashboardOutcomesKeyRoute,
  DashboardRoadmapKeyRoute: DashboardRoadmapKeyRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
